### ISSUE TITLE
Investigate cost of pthread_mutex_t

### ISSUE THREAD

**Issue by lilyball** [postmates/PMKVObserver#1]
When replacing the spinlocks, we added a `pthread_mutex_t` to each observer. We need to profile this to find out how expensive it is to create and destroy these things. And if possible, find out how many system resources a mutex takes as well. If it turns out to be expensive, there's a few reasonable alternatives:
1. Use a `dispatch_queue_t` instead. IIRC they're somewhere on the order of 100-200 bytes, which isn't too bad, and the system should support creating as many of these as we need.
2. Use a bank of mutexes instead, picking one based on a hash of the observer address. This is similar to how the obj-c runtime handles its internal (safe) spinlocks. The benefit is the memory overhead is fixed no matter how many observers we create; the downside is access to a mutex can block because a different observer is using it.
3. Use `@synchronized(self)`. I avoided it because it's not really clear what the runtime behavior of that is; I don't know if it uses a mutex per object, or a bank of mutexes, or even something else.

Hopefully mutexes turn out to be sufficiently cheap that we can keep the current behavior.

**Comment by lilyball** [comment]
#16 also offers an alternative, which is to use `os_unfair_lock` if the OS supports it.

**Comment by Frizlab** [comment]
FWIW, this guy did a pretty good post on `@synchronized` and how it works, including Apple’s implementation which is open-source.
https://www.mikeash.com/pyblog/friday-qa-2015-02-20-lets-build-synchronized.html

**Comment by lilyball** [comment]
I just added support for `os_unfair_lock` in v2.0.2 on platforms that support it. I'm now closing this issue, because `pthread_mutex_t` is now only used on older platforms, and in some basic benchmarking I did it doesn't actually appear to be expensive to create or destroy mutexes.
