### ISSUE TITLE
PMKVObserver is not compatible with Swift 5

### ISSUE THREAD

**Issue by SebastianThiebaud** [postmates/PMKVObserver#21]
Using Xcode 10.2, it seems that changing the build setting `Swift Language Version` to Swift 5 solves the problem. Swift 3 seems unsupported now.

**Comment by lilyball** [comment]
Please update to the latest version. [v4.0.0](https://github.com/postmates/PMKVObserver/releases/tag/v4.0.0) bumped the Swift version to 4.0 (which is still supported by Xcode 10.2).

**Comment by lilyball** [comment]
Also, thanks for using my library!
