### ISSUE TITLE
Crash in dealloc observer

### ISSUE THREAD

**Issue by iwasrobbed** [postmates/PMKVObserver#23]
Hi @lilyball 👋 

This library has been great so far, thanks for your work on it!

I did notice a crash in the dealloc observer when this was use for a camera session, specifically when switching between front and rear cameras.

<img width="1777" alt="KVO crash" src="https://user-images.githubusercontent.com/317671/75513391-d3b55980-5998-11ea-80a4-02944f7e7fd3.png">

We use a single queue for all camera operations.

I can try and put together a repro sample project as well once I get some time to test it in isolation. For now, switching back to normal KVO seems to work fine.

**Comment by lilyball** [comment]
Are you using a key path with multiple dotted components? There's a [known issue](https://github.com/postmates/PMKVObserver/issues/20) with that. The quick fix is to just manually cancel the KVObserver before the object in question deallocates, exactly as you would with "normal" KVO.

**Comment by iwasrobbed** [comment]
There is one key path that is (`\.device.systemPressureState`) so that's likely the cause. Cancelling the observers before the video input deallocs does prevent the crash so I'll close this out. Thank you!

**Comment by lilyball** [comment]
I wish I had a better solution. Ideally I'd put a dealloc spy on every object involved in the chain but I'd basically have to completely rewrite "deep" KVO support to be a series of "shallow" KVOs, which seems like a complete nightmare and is extremely likely to get wrong.

**Comment by iwasrobbed-ks** [comment]
No worries, it sounds a bit brittle to attempt that (and high risk) while offering minimal value in return. For us, the value in this lib is thread safety and easy management. Documentation is a good enough fix for now 👍
