### ISSUE TITLE
Make available on CocoaPods!

### ISSUE THREAD

**Issue by cameronehrlich** [postmates/PMKVObserver#5]

**Comment by tailec** [comment]
+1

**Comment by ldiqual** [comment]
+1

**Comment by magnett** [comment]
+1

**Comment by lilyball** [comment]
I've published a podspec. I don't use CocoaPods myself so I haven't actually tried using it, but `pod spec lint` was happy with it so I think it's good.

**Comment by cameronehrlich** [comment]
:+1:  I'll give it a shot and let you know if it works!

**Comment by bencallis** [comment]
@kballard thanks for adding the podspec. It currently includes the Swift and ObjC files so only works with frameworks. I have opened a PR which includes an update to the podspec with subspecs for Swift and ObjC.

See here https://github.com/postmates/PMKVObserver/pull/7
