### ISSUE TITLE
CocoaPod includes Swift and ObjC

### ISSUE THREAD

**Issue by bencallis** [postmates/PMKVObserver#6]
The current pod spec brings in both the ObjC and Swift files. This means that the pod only works as a framework and any projects which have a dependency on static libraries won't be able to use this.

`- ERROR | [iOS] unknown: Encountered an unknown error (Pods written in Swift can only be integrated as frameworks; add `use_frameworks!` to your Podfile or target to opt into using it. The Swift Pod being used is: PMKVObserver) during validation.`

**Comment by bencallis** [comment]
Opened a PR containing a updated pod pec here https://github.com/postmates/PMKVObserver/pull/7

**Comment by lilyball** [comment]
Closed by #7.
