### ISSUE TITLE
Updated pod spec not pushed to CocoaPods repo

### ISSUE THREAD

**Issue by bencallis** [postmates/PMKVObserver#8]
The latest pod spec with Swift and ObjC subspecs has not been pushed to the central CocoaPod repo so currently can't be used.

Could you please update it.

PR that was merged with the updated spec https://github.com/postmates/PMKVObserver/pull/7

**Comment by lilyball** [comment]
Oops, totally forgot that was a step. Sorry!

**Comment by lilyball** [comment]
D'oh, cocoapods won't let me push the podspec without bumping the version. I don't really want to bump the version of the library just for a cocoapods change but I guess I have no choice.

**Comment by lilyball** [comment]
```
> pod trunk push

[!] Found podspec `PMKVObserver.podspec`
Updating spec repo `master`

Validating podspec
 -> PMKVObserver (1.0.4)

Updating spec repo `master`

  - Data URL: https://raw.githubusercontent.com/CocoaPods/Specs/a07c7192985b4f928086c2a7597ef82859b11e90/Specs/PMKVObserver/1.0.4/PMKVObserver.podspec.json
  - Log messages:
    - March 2nd, 13:21: Push for `PMKVObserver 1.0.4' initiated.
    - March 2nd, 13:21: Push for `PMKVObserver 1.0.4' has been pushed (3.864056919 s).
```

**Comment by bencallis** [comment]
@kballard Thanks very much!

It's very easy to forget :+1:
